# Generated by Django 5.1.4 on 2024-12-16 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detectionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
